services:
  postgres:
    profiles:
      - bundled-db

  backend:
    depends_on: !reset []
    networks:
      - default
      - external_database

networks:
  external_database:
    name: ${MERIDIAN_DATABASE_DOCKER_NETWORK}
    external: true
